// Display labels for subfinder's source IDs (as listed by `subfinder -ls`).
// Falls back to the raw code if a new source is added upstream.
const SOURCE_LABELS: Record<string, string> = {
  alienvault: 'AlienVault',
  anubis: 'Anubis',
  bevigil: 'BeVigil',
  bufferover: 'BufferOver',
  builtwith: 'BuiltWith',
  c99: 'C99',
  censys: 'Censys',
  certspotter: 'CertSpotter',
  chaos: 'Chaos',
  chinaz: 'Chinaz',
  commoncrawl: 'Common Crawl',
  crtsh: 'crt.sh',
  digitalyama: 'DigitalYama',
  digitorus: 'Digitorus',
  dnsdb: 'DNSDB',
  dnsdumpster: 'DNSDumpster',
  dnsrepo: 'DNSRepo',
  domainsproject: 'Domains Project',
  driftnet: 'Driftnet',
  fofa: 'FOFA',
  fullhunt: 'FullHunt',
  github: 'GitHub',
  hackertarget: 'HackerTarget',
  hudsonrock: 'Hudson Rock',
  intelx: 'IntelX',
  leakix: 'LeakIX',
  merklemap: 'MerkleMap',
  netlas: 'Netlas',
  onyphe: 'ONYPHE',
  profundis: 'ProFundis',
  pugrecon: 'PugRecon',
  quake: 'Quake',
  rapiddns: 'RapidDNS',
  reconeer: 'Reconeer',
  redhuntlabs: 'RedHunt Labs',
  robtex: 'Robtex',
  rsecloud: 'RSE Cloud',
  securitytrails: 'SecurityTrails',
  shodan: 'Shodan',
  sitedossier: 'SiteDossier',
  submd: 'Subdomain Center',
  thc: 'THC',
  threatbook: 'ThreatBook',
  threatcrowd: 'ThreatCrowd',
  urlscan: 'urlscan.io',
  virustotal: 'VirusTotal',
  waybackarchive: 'Wayback Machine',
  whoisxmlapi: 'WHOIS XML API',
  windvane: 'Windvane',
  zoomeyeapi: 'ZoomEye',
};

export const getSourceLabel = (code: string) => SOURCE_LABELS[code] ?? code;
