import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ChakraProvider, Container, Flex } from '@chakra-ui/react';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '../styles/globals.css';

const App = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ChakraProvider>
      <Flex minH="100vh" direction="column" align="center" justify="center">
        <Header />

        <Container flex={1}>
          <Component {...pageProps} />
        </Container>

        <Footer />
      </Flex>
    </ChakraProvider>
  </>
);

export default App;
