import { useEffect } from 'react';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { chakra, ChakraProvider, Flex } from '@chakra-ui/react';
import { css } from '@emotion/react';
import { SWRConfig } from 'swr';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/globals.css';

const App = ({ Component, pageProps }: AppProps) => {
  const router = useRouter();

  NProgress.configure({
    showSpinner: false,
  });
  useEffect(() => {
    router.events.on('routeChangeStart', NProgress.start);
    router.events.on('routeChangeComplete', NProgress.done);
    router.events.on('routeChangeError', NProgress.done);

    return () => {
      router.events.off('routeChangeStart', NProgress.start);
      router.events.off('routeChangeComplete', NProgress.done);
      router.events.off('routeChangeError', NProgress.done);
    };
  }, [router]);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SWRConfig
        value={{ fetcher: (url) => fetch(url).then((res) => res.json()) }}
      >
        <ChakraProvider>
          <Flex minH="100vh" direction="column" align="center" justify="center">
            <Header />

            <chakra.div
              css={css(`
            width: 100%;
            `)}
              flex={1}
            >
              <Component {...pageProps} />
            </chakra.div>

            <Footer />
          </Flex>
        </ChakraProvider>
      </SWRConfig>
    </>
  );
};

export default App;
