import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';

import '../styles/globals.css';

const App = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ChakraProvider>
      <Component {...pageProps} />
    </ChakraProvider>
  </>
);

export default App;
